name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build And Push Docker image
      env:
        # 指定自己的仓库地址
        docker_repo: registry.cn-hangzhou.aliyuncs.com/luckywuwuzi
          # 指定镜像名称
        image_name: jsoncracker
          # 指定镜像标签
        tag: latest
      run: docker login --username=${{ secrets.DOCKER_USER }}  --password=${{ secrets.DOCKER_PASSWORD }}  registry.cn-hangzhou.aliyuncs.com        
           docker build . --file Dockerfile --tag $docker_repo/$image_name:$tag
           docker push $docker_repo/$image_name:$tag
